import React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
const Model = dynamic(() => import("../../../components/ModelViewer"), {
  ssr: false,
});
const NFTPage = ({ itemid }) => {
  return (
    <div>
      <Head>
        <title>NFT Page</title>
        <meta name="description" content="Generated by Collection Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <div className="flex justify-center">
          <div className="grid grid-cols-2  w-[900px]   min-h-screen ">
            <div className="flex flex-col  justify-center">
              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <h1>Owner</h1>
                <h1>ID:{itemid.id}</h1>
                <h1>Price</h1>
              </div>
              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <h1>Make Offer</h1>
              </div>

              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <h1>Transactions</h1>
              </div>
            </div>
            <div className=" flex flex-col justify-center items-center  hover:bg-black hover:shadow-2xl p-4 ">
              <Model glb={itemid.glb}></Model>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps = async ({ query, params, req }) => {
  //find NFT ID
  //get all its info
  //render on page
  console.log(query.itemid);
  console.log(query.glb);
  console.log(query.collection);

  return {
    props: {
      // item: items.find((i) => i.name === params?.collection),
      itemid: { id: query.itemid, glb: query.glb },
    },
  };
};

export default NFTPage;
