import React, { useState, useEffect } from "react";
import Head from "next/head";

import dynamic from "next/dynamic";
const Model = dynamic(() => import("../../../components/ModelViewer"), {
  ssr: false,
});

const NFTPage = ({ itemid }) => {
  const [isTabOpen, setisTabOpen] = useState(false);

  useEffect(() => {
    return () => {};
  }, [isTabOpen]);

  return (
    <div>
      <Head>
        <title>NFT Page</title>
        <meta name="description" content="Generated by Collection Page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={
          isTabOpen ? "min-h-screen absolute  md:left-2/4 " : " hidden"
        }
      >
        <div className="w-[300px] md:w-[400px] lg:w-[600px] min-h-screen bg-opacity-80 bg-black text-white  p-2 z-10 relative">
          <div className="w-full min-h-screen flex flex-col justify-center">
            <div className="min-h-[200px] p-2 flex flex-col items-center">
              <h1 className=" text-xl p-2">Current BID Price</h1>
              <h1 className=" text-xl p-2">1 ETH </h1>
              <input
                type="number"
                className="w-3/4 m-2 p-2  bg-white text-black    "
              ></input>
              <button
                className="w-3/4 m-2 bg-white text-black hover:bg-white  p-2 "
                onClick={() => {}}
              >
                Place Bid
              </button>
              <h1 className=" text-xl p-2">Buy Now Price</h1>
              <h1 className=" text-xl p-2">50 ETH </h1>
              <button
                className="bg-white m-2 w-3/4 hover:bg-white text-black  p-2 "
                onClick={() => {}}
              >
                Buy Now
              </button>{" "}
            </div>
            {/* closes tab */}
            <button
              className="bg-white text-black  p-2 m-2 "
              onClick={() => {
                setisTabOpen(!isTabOpen);
              }}
            >
              close
            </button>
          </div>
        </div>
      </div>

      {/* content */}
      <div className="min-h-screen">
        <div className="flex justify-center">
          <div className="grid grid-cols-1 md:grid md:grid-cols-2  w-[900px]   min-h-screen ">
            <div className="flex flex-col  justify-center order-2 md:order-1 ">
              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <h1>Owner</h1>
                <h1>ID:{itemid.id}</h1>
                <h1>Price</h1>
              </div>
              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <button
                  onClick={() => {
                    setisTabOpen(!isTabOpen);
                  }}
                  className=" w-full h-full "
                >
                  Make Offer
                </button>
              </div>

              <div className="w-full hover:shadow-2xl h-[150px] p-4">
                <h1>Transactions</h1>
              </div>
            </div>
            <div className="order-1 md:order-2  flex flex-col justify-center h-[300px] md:min-h-full items-center  hover:bg-black hover:shadow-2xl p-4 ">
              <Model glb={itemid.glb}></Model>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps = async ({ query, params, req }) => {
  //find NFT ID
  //get all its info
  //render on page
  console.log(query.itemid);
  console.log(query.glb);
  console.log(query.collection);

  return {
    props: {
      // item: items.find((i) => i.name === params?.collection),
      itemid: { id: query.itemid, glb: query.glb },
    },
  };
};

export default NFTPage;
