import Head from "next/head";
import Image from "next/image";
import Market from "./market/index";

export default function CollectionsPage() {
  return (
    <div className="min-h-screen ">
      <Head>
        <title>3d Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Market></Market>
    </div>
  );
}
