import React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import Link from "next/link";
import CollectionsGrid from "../../components/Grid/CollectionsGrid";
import CollectionCard from "../../components/Cards/CollectionCard";
import { ThreeScene } from "../../components/three/ThreeScene";

import useRefs from "react-use-refs";
const ModelView = dynamic(() => import("../../components/ModelViewer"), {
  ssr: false,
});
const Market = () => {
  const GlbArr = [
    "1.glb",
    "2.glb",
    "3.glb",
    "4.glb",
    "5.glb",
    "6.glb",
    "7.glb",
    "8.glb",
    "9.glb",
    "10.glb",
    "11.glb",
    "12.glb",
    "13.glb",
    "14.glb",
    "15.glb",
    "16.glb",
    "17.glb",
    "18.glb",
    "19.glb",
  ];

  return (
    <div className="">
      <Head>
        <title>3d Market </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen w-full flex justify-center items-center flex-col ">
        {/*connect metamask  */}
        {/*render nfts!  */}
        {/*  */}

        <div className="w-[300px] md:w-[90%] h-[100vh] mt-2 bg-black">
          <ThreeScene></ThreeScene>
        </div>

        <div className="w-[300px] bg-black h-[500px]">
          <ModelView></ModelView>
        </div>
      </div>

      <CollectionsGrid>
        {/* loops through array  */}
        {GlbArr.map((file, index) => {
          return (
            <CollectionCard
              key={index}
              CollecitonGlb={`/models/${file}`}
              CollectinId={index + 1}
              CollectionName={"Rock 0"}
              ModelComp={<ModelView glb={`/models/${file}`}></ModelView>}
            />
          );
        })}
      </CollectionsGrid>
    </div>
  );
};

export default Market;
