import React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import Link from "next/link";
import CollectionsGrid from "../../components/Grid/CollectionsGrid";
import CollectionCard from "../../components/Cards/CollectionCard";
const ModelView = dynamic(() => import("../../components/ModelViewer"), {
  ssr: false,
});
const Market = () => {
  const GlbArr = [
    "1.glb",
    "2.glb",
    "3.glb",
    "4.glb",
    "5.glb",
    "6.glb",
    "7.glb",
    "8.glb",
  ];

  return (
    <div className="">
      <Head>
        <title>3d Market </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CollectionsGrid>
        {GlbArr.map((file, index) => {
          return (
            <CollectionCard
              key={index}
              CollecitonGlb={`/models/${file}`}
              CollectinId={index + 1}
              CollectionName={"Rock 0"}
              ModelComp={<ModelView glb={`/models/${file}`}></ModelView>}
            />
          );
        })}
      </CollectionsGrid>
    </div>
  );
};

export default Market;
