import React from "react";
import Head from "next/head";
const Home = () => {
  return (
    <div className="min-h-screen ">
      <Head>
        <title>3d Market Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen flex justify-center">
        <div className="w-[800px]"></div>
      </div>
    </div>
  );
};

export default Home;
